apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: castware-api-key
    namespace: castai-agent
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - webhooks.yaml