apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castware-operator.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
