{{- if .Values.webhook.enabled }}
{{- if .Values.webhook.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "castware-operator.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "castware-operator.fullname" . }}-webhook-cert
  issuerRef:
    name: {{ include "castware-operator.fullname" . }}-selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - {{ include "castware-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "castware-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "castware-operator.fullname" . }}-selfsigned-issuer
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "castware-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    {{- include "castware-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "castware-operator.fullname" . }}-webhook-configuration
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "castware-operator.fullname" . }}-webhook-cert"
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: castware-operator-webhook-service
        namespace: castai-agent
        path: /mutate-castware-cast-ai-v1alpha1-cluster
    failurePolicy: Fail
    name: mcluster-v1alpha1.kb.io
    rules:
      - apiGroups:
          - castware.cast.ai
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: castware-operator-webhook-service
        namespace: castai-agent
        path: /mutate-castware-cast-ai-v1alpha1-component
    failurePolicy: Fail
    name: mcomponent-v1alpha1.kb.io
    rules:
      - apiGroups:
          - castware.cast.ai
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - components
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "castware-operator.fullname" . }}-webhook-configuration
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "castware-operator.fullname" . }}-webhook-cert"
  {{- end }}
webhooks:
- name: vcluster.kb.io
  rules:
  - apiGroups: ["castware.cast.ai"]
    apiVersions: ["v1alpha1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["clusters"]
    scope: "Namespaced"
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "castware-operator.fullname" . }}-webhook-service
      path: /validate-castware-cast-ai-v1alpha1-cluster
      port: 443
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10
- name: vcomponent.kb.io
  rules:
  - apiGroups: ["castware.cast.ai"]
    apiVersions: ["v1alpha1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["components"]
    scope: "Namespaced"
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "castware-operator.fullname" . }}-webhook-service
      path: /validate-castware-cast-ai-v1alpha1-component
      port: 443
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10
{{- end }}
