---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-castware-cast-ai-v1alpha1-cluster
  failurePolicy: Fail
  name: mcluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - castware.cast.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-castware-cast-ai-v1alpha1-component
  failurePolicy: Fail
  name: mcomponent-v1alpha1.kb.io
  rules:
  - apiGroups:
    - castware.cast.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - components
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-castware-cast-ai-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - castware.cast.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-castware-cast-ai-v1alpha1-component
  failurePolicy: Fail
  name: vcomponent-v1alpha1.kb.io
  rules:
  - apiGroups:
    - castware.cast.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - components
  sideEffects: None
