{{- if .Values.apiKeySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiKeySecret.name | default "castware-api-key" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ required ".Values.apiKeySecret.apiKey is required" .Values.apiKeySecret.apiKey | quote }}
{{- end }}
