{{- if .Values.apiKeySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiKeySecret.name | default "castware-api-key" }}
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.apiKeySecret.apiKey | b64enc }}
{{- end }}
