{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "castware-operator.fullname" . }}-controller-manager
  labels:
    {{- include "castware-operator.labels" . | nindent 4 }}
{{- end }}