# This rule is not used by the project castware-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the castware.cast.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: castware-operator
    app.kubernetes.io/managed-by: kustomize
  name: castware-editor-role
rules:
- apiGroups:
  - castware.cast.ai
  resources:
  - castwares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - castware.cast.ai
  resources:
  - castwares/status
  verbs:
  - get
