apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-system-access
  namespace: kube-system
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-system-access
  namespace: kube-system
roleRef:
  kind: Role
  name: castware-operator-kube-system-access
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: castware-operator-controller-manager
    namespace: castai-agent
