# rolebinding-namespace-admin.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-role-binding
  namespace: castai-agent
subjects:
  - kind: ServiceAccount
    name: castware-operator-controller-manager
    namespace: castai-agent
roleRef:
  kind: Role
  name: namespace-role
  apiGroup: rbac.authorization.k8s.io
