apiVersion: castware.cast.ai/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: castware-operator
    app.kubernetes.io/managed-by: kustomize
  namespace: castai-agent
  name: castai
spec:
  provider: gke
  api:
    apiUrl: "" #Set API url
