---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: castai-agent
    app.kubernetes.io/name: castai-agent
  name: castai-agent
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: castai-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: castai-agent
  name: castware-api-key
  namespace: castai-agent
data:
  API_KEY: "NmI2NmIxMmExZmZmYThiNmY2Nzc0NTc0NTkxYzQzMDE1ZjBjMTY2NjlkMzFkZTdlYzdmMDk3MjAxZGJiMzRjZQ==" #Insert your API key here
---
apiVersion: castware.cast.ai/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: castware-operator
    app.kubernetes.io/managed-by: kustomize
  namespace: castai-agent
  name: castai
spec:
  provider: gke
  api:
    apiUrl: https://api.dev-master.cast.ai
  # TODO(user): Add fields here
