apiVersion: castware.cast.ai/v1alpha1
kind: Castware
metadata:
  labels:
    app.kubernetes.io/name: castware-operator
    app.kubernetes.io/managed-by: kustomize
  name: castware-sample
spec:
  # TODO(user): Add fields here
