apiVersion: castware.cast.ai/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: castware-operator
    app.kubernetes.io/managed-by: kustomize
  name: castware-sample
spec:
  # TODO(user): Add fields here
---
apiVersion: castware.cast.ai/v1alpha1
kind: Component
metadata:
  labels:
    app.kubernetes.io/name: castware-operator
    app.kubernetes.io/managed-by: kustomize
  name: castware-sample
spec:
# TODO(user): Add fields here


operator-sdk create webhook --version=v1alpha1 --group castware.cast.ai --kind=Cluster --defaulting --programmatic-validation
operator-sdk create webhook --version=v1alpha1 --group castware.cast.ai --kind=Component --defaulting --programmatic-validation
