apiVersion: castware.cast.ai/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: castware-operator
    app.kubernetes.io/managed-by: kustomize
  name: castware-sample
spec:
  api:
    apiUrl: https://api--niccolos-macbook-pro.local.cast.ai
  # TODO(user): Add fields here
