components:
  castai-agent:
    component: "castai-agent"
    cluster: "castai"
    enabled: true

namespace: "castai-agent"
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1005
  runAsGroup: 1005
  runAsUser: 1005
  seccompProfile:
    type: RuntimeDefault

checkOperator:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: "v1.25.4"
    pullPolicy: IfNotPresent
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 1005
    runAsGroup: 1005
    runAsUser: 1005
    seccompProfile:
      type: RuntimeDefault
